# -*- coding: utf-8 -*-
"""Sentimen_Analisis_Review_StardewValley_Play_Store-Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zpdb3uznLN-74PfayCwf3x5_g971g3s7

# Notebook for Scraping Dataset : Stardew Valley APK Play Store

- **Nama:** Abid Juliant Indraswara
- **Email:** abidjuliant@gmail.com
- **ID Dicoding:** abidindraswara

Scraping dataset untuk projek sentimen analisis NLP dengan studi kasus review atau ulasan pada aplikasi game mobile Stardew Valley yang di scrape melalui ulasan Play Store.

## Import Library Scraper

Perlu menginstall library scraper google playstore karena colaboratory belum memiliki library native untuk scrape data dari play store.

Dokumentasi Library for Scrape : https://pypi.org/project/google-play-scraper/
"""

# install library scraper google playstore
!pip install google-play-scraper

# import library yang dibutuhkan
from google_play_scraper import app, reviews, Sort, reviews_all
import pandas as pd
import csv

"""## Scraping Dataset

- Aplikasi ID Stardew Valley : com.chucklefish.stardewvalley
- Bahasa dan Negara Review   : English/US
- Jumlah Data                : None atau semuanya
"""

scrapreview = reviews_all(
    'com.chucklefish.stardewvalley',          # ID aplikasi
    lang='en',                                # Bahasa ulasan (default: 'en')
    country='us',                             # Negara (default: 'us')
    sort=Sort.MOST_RELEVANT,                  # Urutan ulasan (default: Sort.MOST_RELEVANT)
    count=None                                # Jumlah maksimum ulasan yang ingin diambil
)

"""## Check Dataset"""

app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df.shape

app_reviews_df

app_reviews_df.info()

"""## Ekspor Dataset"""

# Ekspor dataset review all column
app_reviews_df.to_csv('stardew_us_review.csv', index=None, header=True)

# Ekspor data review ke dalam bentuk csv file hanya untuk kolom Review
with open('stardew_us_review_header.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review']) # Memilih header atau nama kolom yang diinginkan
    for review in scrapreview:
        writer.writerow([review['content']])  # Menulis konten review ke dalam file CSV

!pip freeze requirements.txt

"""## Lanjut ke notebook.ipynb untuk pengolahan dataset hingga menjadi model siap pakai ..."""